apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sfmet73ck-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sfmet73ck-nodejs 
  name: sfmet73ck-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: sfmet73ck-nodejs 
